email:
  username: jbloom.lab.sock.swap@gmail.com
  password: secret_password.txt
exclusion_list:
  - ["Jesse Bloom", "Aster Bloom"]
  - ["Jesse Bloom", "Alice Bloom"]
  - ["Alice Bloom", "Aster Bloom"]
